spring:
  application:
    name: EurekaRegistry
    
server:
  port: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/    register-with-eureka: false
    fetch-registry: false
      
